<html>
    <head>

    </head>

    <body>
        <script>
            //Promise会吃掉错误

            const p1 = new Promise((resolve, reject) => {
                console.info("p1 beginning!");
                return setTimeout(() => reject(new Error("Error.")), 3000);
                // console.info("p1 end!");    //一般来说，对于promise来说，执行完reject，resolve之后，他的任务就算完成了

            });

            const p2 = new Promise((resolve, reject) => {
                console.info("p2 beginning!");
                setTimeout(() => resolve(p1), 1000);
                console.info("p2 end!");  //一般来说，对于promise来说，执行完reject，resolve之后，他的任务就算完成了
            });

            p2.then(result => {
                console.info("then");
                console.info(result);
            }).catch(error => {
                console.info("catch");
                console.info(error);
            });

        </script>


    </body>
</html>